### ISSUE TITLE
Application forms are missing

### ISSUE THREAD

**Issue by pranayjoshi** [AICode-In/AICode-In#1]
**Describe the bug**
Submission or application forms are not loading. well its just a fun issue, I can understand they might be in progress

**To Reproduce**
1. clicking on applying gives a strange output

**Expected behavior**
A form or login page must open.

**Additional context**
Well I saw you followed me and so do I, than I got a notification that you created a new org and a new repo so I got it a look

**Comment by chinglamchoi** [comment]
Hey and thanks so much! Yes it's definitely WIP, we'll be updating everything soon!
